// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: 6818

#ifndef _6818_UI_H
#define _6818_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * file_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * file2_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * liang_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bj_png);    // assets/bj.png
LV_IMG_DECLARE(ui_img_zhuangshi_png);    // assets/zhuangshi.png
LV_IMG_DECLARE(ui_img_sudupan_png);    // assets/sudupan.png
LV_IMG_DECLARE(ui_img_youm_png);    // assets/youm.png
LV_IMG_DECLARE(ui_img_fill_1_png);    // assets/Fill 1.png
LV_IMG_DECLARE(ui_img_shace_png);    // assets/shace.png
LV_IMG_DECLARE(ui_img_right6_png);    // assets/right6.png
LV_IMG_DECLARE(ui_img_faguangtiao_png);    // assets/faguangtiao.png
LV_IMG_DECLARE(ui_img_ring_left_small_png);    // assets/ring_left_small.png
LV_IMG_DECLARE(ui_img_ring_right_small_png);    // assets/ring_right_small.png
LV_IMG_DECLARE(ui_img_seatbelt_big_png);    // assets/seatbelt_big.png
LV_IMG_DECLARE(ui_img_xxd_png);    // assets/xxd.png
LV_IMG_DECLARE(ui_img_icon_play_png);    // assets/icon_play.png
LV_IMG_DECLARE(ui_img_icon_skip_next_png);    // assets/icon_skip_next.png
LV_IMG_DECLARE(ui_img_icon_skip_prev_png);    // assets/icon_skip_prev.png
LV_IMG_DECLARE(ui_img_icon_playlist_png);    // assets/icon_playlist.png
LV_IMG_DECLARE(ui_img_icon_back_png);    // assets/icon_back.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);
LV_FONT_DECLARE(ui_font_Font4);
LV_FONT_DECLARE(ui_font_Font45);
LV_FONT_DECLARE(ui_font_Font5);
LV_FONT_DECLARE(ui_font_Font7);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
