ARG BASE_OS=debian:bookworm
FROM ${BASE_OS}

RUN DEBIAN_FRONTEND="noninteractive" apt-get update

# Build tools
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y make cmake build-essential python3-venv

# SDL
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y libsdl2-dev libsdl2-image-dev

# DRM/evdev (linux-headers-amd64 for Debian, linux-headers-generic for Ubuntu)
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y libevdev-dev libdrm-dev linux-headers-amd64 || \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y libevdev-dev libdrm-dev linux-headers-generic

RUN mkdir /workdir
WORKDIR /workdir
