// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: 6818

#include "../ui.h"
#include "../../account.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Enter = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_LoginMsg = NULL;
// event funtions
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea2);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Enter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        const char *username = lv_textarea_get_text(ui_TextArea1);
        const char *password = lv_textarea_get_text(ui_TextArea2);

        if (account_login(username, password) == 0) {
            lv_label_set_text(ui_LoginMsg, "True");
            lv_obj_set_style_text_color(ui_LoginMsg, lv_color_hex(0x00AA00), 0);
            _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
        } else {
            lv_label_set_text(ui_LoginMsg, "False");
            lv_obj_set_style_text_color(ui_LoginMsg, lv_color_hex(0xFF0000), 0);
        }
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_bj_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 357);
    lv_obj_set_height(ui_Panel1, 396);
    lv_obj_set_x(ui_Panel1, 5);
    lv_obj_set_y(ui_Panel1, -15);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xBAB9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 270);
    lv_obj_set_height(ui_TextArea1, 40);
    lv_obj_set_x(ui_TextArea1, 2);
    lv_obj_set_y(ui_TextArea1, -100);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "请输入账号");
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea2, 270);
    lv_obj_set_height(ui_TextArea2, 40);
    lv_obj_set_x(ui_TextArea2, 2);
    lv_obj_set_y(ui_TextArea2, -50);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "请输入密码");
    lv_textarea_set_password_mode(ui_TextArea2, true);
    lv_obj_set_style_text_font(ui_TextArea2, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label4, -2);
    lv_obj_set_y(ui_Label4, -164);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "你好，用户");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x292828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Enter = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Enter, 100);
    lv_obj_set_height(ui_Enter, 50);
    lv_obj_set_x(ui_Enter, -84);
    lv_obj_set_y(ui_Enter, 99);
    lv_obj_set_align(ui_Enter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Enter, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Enter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Enter);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "登录");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 74);
    lv_obj_set_y(ui_Button2, 99);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "注册");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 801);
    lv_obj_set_height(ui_Keyboard1, 209);
    lv_obj_set_x(ui_Keyboard1, -1);
    lv_obj_set_y(ui_Keyboard1, 135);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_LoginMsg = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LoginMsg, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LoginMsg, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LoginMsg, 0);
    lv_obj_set_y(ui_LoginMsg, 10);
    lv_obj_set_align(ui_LoginMsg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoginMsg, "");

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Enter, ui_event_Enter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image2 = NULL;
    ui_Panel1 = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_Label4 = NULL;
    ui_Enter = NULL;
    ui_Label2 = NULL;
    ui_Button2 = NULL;
    ui_Label3 = NULL;
    ui_Keyboard1 = NULL;
    ui_LoginMsg = NULL;

}
