// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: 6818

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image12;
extern void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern void ui_event_Image14(lv_event_t * e);
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Image17;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label11;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

