// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: 6818

#include "../ui.h"
#include "../../video_play.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image19 = NULL;
// event funtions
void ui_event_Screen4_load(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_SCREEN_LOAD_START) {
        video_play_start();
    }
}

void ui_event_Image19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        video_play_stop();
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image1, &ui_img_xxd_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel3, 800);
    lv_obj_set_height(ui_Panel3, 400);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -40);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image4, &ui_img_icon_play_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 200);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider2 = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 800);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, 150);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image5 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image5, &ui_img_icon_skip_next_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image5, 50);
    lv_obj_set_y(ui_Image5, 200);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image6, &ui_img_icon_skip_prev_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image6, -50);
    lv_obj_set_y(ui_Image6, 200);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image18, &ui_img_icon_playlist_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image18, 100);
    lv_obj_set_y(ui_Image18, 200);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image19, &ui_img_icon_back_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image19, -360);
    lv_obj_set_y(ui_Image19, 200);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image19, ui_event_Image19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4_load, LV_EVENT_SCREEN_LOAD_START, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Image1 = NULL;
    ui_Panel3 = NULL;
    ui_Image4 = NULL;
    ui_Slider2 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Image18 = NULL;
    ui_Image19 = NULL;

}
