// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: 6818

#include "../ui.h"
#include "../../account.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_TextArea4 = NULL;
lv_obj_t * ui_TextArea5 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_TextArea4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea4);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_TextArea5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea5);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        const char *username = lv_textarea_get_text(ui_TextArea4);
        const char *password = lv_textarea_get_text(ui_TextArea5);

        if (account_register(username, password) == 0) {
            _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        }
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_Image3, &ui_img_xxd_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, 423);
    lv_obj_set_height(ui_Panel2, 323);
    lv_obj_set_x(ui_Panel2, -1);
    lv_obj_set_y(ui_Panel2, -5);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -142);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "创建账户");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea4, 270);
    lv_obj_set_height(ui_TextArea4, 40);
    lv_obj_set_x(ui_TextArea4, 3);
    lv_obj_set_y(ui_TextArea4, -90);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "请输入账号");
    lv_obj_set_style_text_font(ui_TextArea4, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea5 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea5, 270);
    lv_obj_set_height(ui_TextArea5, 40);
    lv_obj_set_x(ui_TextArea5, 3);
    lv_obj_set_y(ui_TextArea5, -20);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "请输入密码");
    lv_textarea_set_password_mode(ui_TextArea5, true);
    lv_obj_set_style_text_font(ui_TextArea5, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_x(ui_Button7, 0);
    lv_obj_set_y(ui_Button7, 80);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "注册");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Keyboard2, 800);
    lv_obj_set_height(ui_Keyboard2, 250);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 120);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea5, ui_event_TextArea5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image3 = NULL;
    ui_Panel2 = NULL;
    ui_Label5 = NULL;
    ui_TextArea4 = NULL;
    ui_TextArea5 = NULL;
    ui_Button7 = NULL;
    ui_Label6 = NULL;
    ui_Keyboard2 = NULL;

}
