// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: 6818

#include "../ui.h"
#include "../../ui_arc_auto_decrease.h"
#include "../../ui_turn_signal.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Arc2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label12 = NULL;

// 速度挡位：1=一挡(慢), 2=二挡(快)
static int ui_Arc1_gear = 1;

// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        liang_Animation(ui_Image17, 20);
    }
}

void ui_event_Image13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        int inc = (ui_Arc1_gear == 1) ? 1 : 10;   // 一挡+1, 二挡+10
        _ui_arc_increment(ui_Arc1, inc);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        file_Animation(ui_Image12, 100);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_arc_increment(ui_Arc2, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        file_Animation(ui_Image9, 100);
    }
}

void ui_event_Arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label1, target, "", "");
    }
}

void ui_event_Image14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_arc_increment(ui_Arc1, -4);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        file2_Animation(ui_Image12, 0);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_arc_increment(ui_Arc2, -4);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        file2_Animation(ui_Image9, 0);
    }
}

void ui_event_Arc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label10, target, "", "");
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_Arc1_gear = 1;  // 一挡：慢速
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_Arc1_gear = 2;  // 二挡：快速
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen4_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image10, &ui_img_zhuangshi_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 202
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 258
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image11, &ui_img_sudupan_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 374
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 335
    lv_obj_set_x(ui_Image11, -218);
    lv_obj_set_y(ui_Image11, -49);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image13, &ui_img_youm_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image13, -301);
    lv_obj_set_y(ui_Image13, 190);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -213);
    lv_obj_set_y(ui_Label1, 16);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "0");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image12, &ui_img_fill_1_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image12, -218);
    lv_obj_set_y(ui_Image12, 24);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image12, -1300);

    ui_Arc1 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Arc1, 242);
    lv_obj_set_height(ui_Arc1, 250);
    lv_obj_set_x(ui_Arc1, -210);
    lv_obj_set_y(ui_Arc1, 23);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 0, 200);
    lv_arc_set_value(ui_Arc1, 0);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x40E4FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image14 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image14, &ui_img_shace_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image14, 301);
    lv_obj_set_y(ui_Image14, 190);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image7, &ui_img_right6_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 374
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 335
    lv_obj_set_x(ui_Image7, 206);
    lv_obj_set_y(ui_Image7, -39);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image8, &ui_img_faguangtiao_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 468
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 283
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, 19);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc2 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_Arc2, 211);
    lv_obj_set_height(ui_Arc2, 213);
    lv_obj_set_x(ui_Arc2, 203);
    lv_obj_set_y(ui_Arc2, 23);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc2, 0, 10);
    lv_arc_set_value(ui_Arc2, 0);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xFF40BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xFF40E8), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 205);
    lv_obj_set_y(ui_Label10, 19);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "0");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image9, &ui_img_fill_1_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 105
    lv_obj_set_x(ui_Image9, 203);
    lv_obj_set_y(ui_Image9, 16);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image9, -1300);

    ui_Image15 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image15, &ui_img_ring_left_small_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image15, -4);
    lv_obj_set_y(ui_Image15, 73);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image16, &ui_img_ring_right_small_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_Image16, 4);
    lv_obj_set_y(ui_Image16, 73);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 50);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -68);
    lv_obj_set_y(ui_Button1, 188);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xD11818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "left");

    ui_Button3 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 50);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 68);
    lv_obj_set_y(ui_Button3, 188);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xD11818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "right");

    ui_Image17 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Image17, &ui_img_seatbelt_big_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image17, -132);
    lv_obj_set_y(ui_Image17, 190);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 50);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 357);
    lv_obj_set_y(ui_Button4, -207);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x0A588B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "视频");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button5, 50);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, 130);
    lv_obj_set_y(ui_Button5, 188);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "一挡");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button6, 50);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 190);
    lv_obj_set_y(ui_Button6, 188);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "二挡");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image13, ui_event_Image13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image14, ui_event_Image14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

    ui_arc_auto_decrease_init(ui_Arc1,ui_Image13,-2,30);
    ui_arc_auto_decrease_init(ui_Arc2,ui_Image13,-2,30);
    ui_turn_signal_init(ui_Button1,ui_Button3,ui_Image15,ui_Image16,500);


}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image13 = NULL;
    ui_Label1 = NULL;
    ui_Image12 = NULL;
    ui_Arc1 = NULL;
    ui_Image14 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Arc2 = NULL;
    ui_Label10 = NULL;
    ui_Image9 = NULL;
    ui_Image15 = NULL;
    ui_Image16 = NULL;
    ui_Button1 = NULL;
    ui_Label7 = NULL;
    ui_Button3 = NULL;
    ui_Label8 = NULL;
    ui_Image17 = NULL;
    ui_Button4 = NULL;
    ui_Label9 = NULL;
    ui_Button5 = NULL;
    ui_Label11 = NULL;
    ui_Button6 = NULL;
    ui_Label12 = NULL;

}
